# simulator/Dockerfile
FROM python:3.12-slim
FROM python:3.11-slim
WORKDIR /app
COPY simulator.py .
RUN pip install requests
# Las variables (API_BASE, POZOS, etc.) se pasan por docker-compose.yml
CMD ["python", "simulator.py"]
